CREATE TABLE Usuario (
    id_usuario INT PRIMARY KEY IDENTITY(1,1),
    nome NVARCHAR(100) NOT NULL,
    login NVARCHAR(50) NOT NULL UNIQUE,
    senha NVARCHAR(255) NOT NULL,
    email NVARCHAR(100) NOT NULL UNIQUE
);
GO